version: "3.5"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017:27017
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
  api:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: on-failure
